### PR TITLE
Add trusty-backports ppa, for swig3.0 in Ubuntu trusty

### PR DESCRIPTION
**Pull request by poppingtonic**
- swig3.0 isn't in the main package repository in Ubuntu, so I added the [trusty-backports](https://launchpad.net/~tsvetko.tsvetkov/+archive/ubuntu/trusty-backports) ppa, which contains it.

### CODE REVIEW

**Comment by vaporos** [comment]
With the default Vagrantfile provided, which uses the ubuntu/trusty64 box file, I'm seeing swig3.0 pulled in from the trust-backports repository (defined in /etc/apt/sources.list).

Are you using a different box file?

**Comment by poppingtonic** [comment]
No, I haven't changed a thing in the Vagrantfile.  `ubuntu/trusty64` doesn't have trusty-backports installed. Did you run your test on my branch or in the currently updated `master`? trusty-backports wasn't there before I added the line to `sudo add-apt-repository`. When I ran `vagrant up` right after cloning, the provisioning failed with `could not find swig3.0` I did this twice to see if the problem was my network. When I added the ppa, it passed that step.

**Comment by poppingtonic** [comment]
I see what you mean:

```bash
vagrant@vagrant-ubuntu-trusty-64:/project$ grep -n "trusty-backports" /etc/apt/sources.list
45:deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse
46:deb-src http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse

vagrant@vagrant-ubuntu-trusty-64:/project$ cat /etc/apt/sources.list.d/tsvetko_tsvetkov-trusty-backports-trusty.list
deb http://ppa.launchpad.net/tsvetko.tsvetkov/trusty-backports/ubuntu trusty main
# deb-src http://ppa.launchpad.net/tsvetko.tsvetkov/trusty-backports/ubuntu trusty main
# deb-src http://ppa.launchpad.net/tsvetko.tsvetkov/trusty-backports/ubuntu trusty main
# deb-src http://ppa.launchpad.net/tsvetko.tsvetkov/trusty-backports/ubuntu trusty main
# deb-src http://ppa.launchpad.net/tsvetko.tsvetkov/trusty-backports/ubuntu trusty main
```
I still wonder why it failed, though, while succeeding with tsvetkov's ppa.

**Comment by vaporos** [comment]
Could you capture the error which occurs during 'vagrant up'?  Primarily, wondering if there is a network/proxy issue which is allowing connections to ppa.launchpad.net but not archive.ubuntu.com, or some other network explanation.

Thanks!

**Comment by vaporos** [comment]
Closing since the trusty-backports repo is already enabled in sources.list.

**Comment by poppingtonic** [comment]
I pulled a fresh copy and ran `vagrant up`. It worked, so I'm assuming that the previous attempts were stymied by a recurring network problem that only affected access to the package repository.

**Pull request closed without merging**
